import express from "express";
import cors from "cors";
import multer from "multer";
import crypto from "crypto";
import "dotenv/config";

const app=express(); app.use(cors()); app.use(express.json());
const upload=multer({dest:"uploads/",limits:{fileSize:1024*1024*1024}});
const sessions=new Map();
const need=k=>{if(!process.env[k])throw new Error(`Missing ${k}`);return process.env[k]};
app.get("/health",(_req,res)=>res.json({ok:true,service:"RAFLI V5"}));

app.post("/api/link/start",async(_req,res)=>{try{const link_id=crypto.randomUUID(),state=crypto.randomBytes(24).toString("hex");sessions.set(link_id,{state,linked:false});const q=new URLSearchParams({client_key:need("TIKTOK_CLIENT_KEY"),response_type:"code",scope:"video.upload",redirect_uri:need("TIKTOK_REDIRECT_URI"),state:`${link_id}.${state}`});res.json({link_id,auth_url:`https://www.tiktok.com/v2/auth/authorize/?${q}`})}catch(e){res.status(500).json({error:String(e.message||e)})}});

app.get("/auth/tiktok/callback",async(req,res)=>{try{const code=String(req.query.code||""),stateRaw=String(req.query.state||"");const [link_id,state]=stateRaw.split(".");const s=sessions.get(link_id);if(!s||s.state!==state||!code)return res.status(400).send("Invalid state/code");const body=new URLSearchParams({client_key:need("TIKTOK_CLIENT_KEY"),client_secret:need("TIKTOK_CLIENT_SECRET"),code,grant_type:"authorization_code",redirect_uri:need("TIKTOK_REDIRECT_URI")});const r=await fetch("https://open.tiktokapis.com/v2/oauth/token/",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body});const d=await r.json();if(!r.ok||!d.access_token)return res.status(400).send("Token exchange failed");Object.assign(s,{linked:true,access_token:d.access_token,refresh_token:d.refresh_token,expires_at:Date.now()+Number(d.expires_in||86400)*1000,open_id:d.open_id||""});res.send("<html><body><h2>RAFLI ✅</h2><p>TikTok connected. Return to RAFLI.</p></body></html>")}catch(e){res.status(500).send(String(e.message||e))}});
app.get("/api/link/status",(req,res)=>{const s=sessions.get(String(req.query.link_id||""));res.json({linked:!!s?.linked,username:s?.display_name||null})});

async function ensureToken(s){if(!s?.linked)throw new Error("TikTok is not linked");if(Date.now()<(s.expires_at||0)-120000)return s.access_token;if(!s.refresh_token)throw new Error("Missing refresh token");const body=new URLSearchParams({client_key:need("TIKTOK_CLIENT_KEY"),client_secret:need("TIKTOK_CLIENT_SECRET"),grant_type:"refresh_token",refresh_token:s.refresh_token});const r=await fetch("https://open.tiktokapis.com/v2/oauth/token/",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body});const d=await r.json();if(!r.ok||!d.access_token)throw new Error("TikTok token refresh failed");s.access_token=d.access_token;s.refresh_token=d.refresh_token||s.refresh_token;s.expires_at=Date.now()+Number(d.expires_in||86400)*1000;return s.access_token}

app.post("/api/tiktok/upload-draft",upload.single("video"),async(req,res)=>{try{const s=sessions.get(String(req.body.link_id||"")),token=await ensureToken(s);if(!req.file)return res.status(400).json({ok:false,message:"No video"});const fs=await import("fs"),size=req.file.size;const init=await fetch("https://open.tiktokapis.com/v2/post/publish/inbox/video/init/",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json; charset=UTF-8"},body:JSON.stringify({source_info:{source:"FILE_UPLOAD",video_size:size,chunk_size:size,total_chunk_count:1}})});const id=await init.json();if(!init.ok||!id?.data?.upload_url)throw new Error(JSON.stringify(id));const bytes=fs.readFileSync(req.file.path);const put=await fetch(id.data.upload_url,{method:"PUT",headers:{"Content-Type":"video/mp4","Content-Length":String(size),"Content-Range":`bytes 0-${size-1}/${size}`},body:bytes});fs.unlink(req.file.path,()=>{});if(!put.ok)throw new Error(`TikTok binary upload failed ${put.status}`);res.json({ok:true,publish_id:id.data.publish_id||null})}catch(e){if(req.file){const fs=await import("fs");fs.unlink(req.file.path,()=>{})}res.status(500).json({ok:false,message:String(e.message||e)})}});

app.get("/api/tiktok/status",async(req,res)=>{try{const link_id=String(req.query.link_id||""),publish_id=String(req.query.publish_id||"");if(!publish_id)return res.status(400).json({ok:false,message:"Missing publish_id"});const token=await ensureToken(sessions.get(link_id));const r=await fetch("https://open.tiktokapis.com/v2/post/publish/status/fetch/",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json; charset=UTF-8"},body:JSON.stringify({publish_id})});const d=await r.json();if(!r.ok||d?.error?.code!=="ok")return res.status(r.status||500).json({ok:false,message:d?.error?.message||d?.error?.code||"TikTok status failed"});const x=d.data||{};res.json({ok:true,status:x.status||null,fail_reason:x.fail_reason||null,uploaded_bytes:Number(x.uploaded_bytes||0),post_ids:(x.publicaly_available_post_id||[]).map(String)})}catch(e){res.status(500).json({ok:false,message:String(e.message||e)})}});
app.listen(process.env.PORT||3000,()=>console.log("RAFLI V5 backend ready"));
